apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 2
  selector:
    # specify how the Deployment selects which Pods to manage.
    # In this case, select Pods with the label "app: nginx"
    matchLabels:
      app: nginx
  template:
    # Pods created by this deployment inherit these settings
    metadata:
      # Labels to apply to the pods
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        # Where and how mount a volume into a specific container within a Pod
        # In this case, mount ConfigMap "nginx-config-1" into the path "/usr/share/nginx/html"
        - name: nginx-html-content
          mountPath: /usr/share/nginx/html
      volumes:
      # Handle persistent and shared data across containers within a Pod
      - name: nginx-html-content
        configMap:
          # Share data from the ConfigMap
          name: nginx-config-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html-content
        configMap:
          name: nginx-config-2
