apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80
          name: nginx-cont-port


